### ISSUE TITLE
Allow for deciding if you want to run `release new` and/or `release finalize`

### ISSUE THREAD

**Issue by JCQuintas** [getsentry/sentry-dart-plugin#102]
My use case: 

- Our web build is done on a different tool than our mobile builds. 
- In the web step, we wanted to run the tool to `new release`, `upload_source_maps` and `upload_sources`.
- In the mobile build, we wanted to run the tool to `upload_debug_symbols` and `finalise release`.

Not sure which would be the ideal API for this, but I thought of two possible options.

Simply define if release new/finalize should run:
- `release_new`: `bool`
- `release_finalize`: `bool`

Define the command order for all commands, possibly breaking:
- `command_order`: `release_new|upload_source_maps|release_finalize`

**Comment by marandaneto** [comment]
@JCQuintas I understand the issue but this seems to be specific to your setup, it's not common to split up the build this way.
You can use [sentry-cli](https://docs.sentry.io/product/cli/) directly for that.
Another option is adding a `release_finalize: bool = true` as you suggested, are you willing to contribute with a PR?

**Comment by marandaneto** [comment]
@JCQuintas did it work using sentry-cli directly?

**Comment by JCQuintas** [comment]
Hey @marandaneto using the CLI works, yes

**Comment by marandaneto** [comment]
Alright, since this is a very corner case, I'd tell this is the way to go, glad that it worked out.
