### ISSUE TITLE
stderr: error: could not find repository from '.'; class=Repository (6); code=NotFound (-3)

### ISSUE THREAD

**Issue by PawlikMichal25** [getsentry/sentry-dart-plugin#120]
### Environment
```
Flutter: 3.7.12

sentry_flutter: 7.5.2
sentry_dart_plugin: 1.2.0
```
### Steps to Reproduce
1. Configure Sentry in pubspec.yaml:
```
sentry:
  upload_debug_symbols: true
  project: vosbor-mobile
  org: vosbor-exchange-bv
  auth_token: XXXX
  wait_for_processing: true
```
2. Create new Flutter project 
3. Run `flutter build apk --obfuscate --split-debug-info=symbols`
4. Run `flutter packages pub run sentry_dart_plugin`

### Expected Result

It uploads debug symbols and doesn't complain about random things.

### Actual Result
It successfully uploads symbols and I can see readable issues on Sentry's panel, but at the same time the command complains about some repository and fails the whole command, which messes with CI.

What is this repository? How can I fix this?

<details>
  <summary>Full output</summary>
  
  ```
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 0% reading config values..        
Downloading sentry-cli from https://downloads.sentry-cdn.com/sentry-cli/2.17.5/sentry-cli-Darwin-universal to .dart_tool/pub/bin/sentry_dart_plugin/sentry-cli

Downloaded Sentry CLI binary checksum verification passed successfully (hash: XXXXX).

Sentry CLI downloaded successfully.
☑ reading config values                                                             
☑ validating config values                                                             
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 18% uploading debug symbols..                                
includeSources is disabled, not uploading sources.

stderr: 
stdout: > Found 65 debug information files
> Prepared debug information files for upload
> Uploaded 6 missing debug information files
> File processing complete:

       OK 5fc867f4-1791-fbcf-69d0-20a6d69dbca6 (app.android-arm.symbols; arm debug companion)
       OK bf4aa6bc-93cb-d970-31bb-8f1c70ef2ceb (app.android-arm64.symbols; arm64 debug companion)
       OK 8e504493-c779-358b-4c94-298242f84e77 (app.android-x64.symbols; x86_64 debug companion)
       OK bf4aa6bc-93cb-d970-31bb-8f1c70ef2ceb (app.so; arm64 library)
       OK 5fc867f4-1791-fbcf-69d0-20a6d69dbca6 (app.so; arm library)
       OK 8e504493-c779-358b-4c94-298242f84e77 (app.so; x86_64 library)

☑ uploading debug symbols                                                             

stderr: 
stdout: Created release my_project@1.0.0+1


uploadSourceMaps is disabled.

exitCode: 1
stderr: error: could not find repository from '.'; class=Repository (6); code=NotFound (-3)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

stdout: 
pub finished with exit code 1


  ```
  
</details>

**Comment by marandaneto** [comment]
@PawlikMichal25 thanks for raising.
can you run again with the `log_level: true` for more detailed logs?

@kamilogorek have you seen this already?

**Comment by marandaneto** [comment]
@PawlikMichal25 can you also try to `commits: false`?

**Comment by marandaneto** [comment]
@PawlikMichal25 the `fca` title is because of https://github.com/getsentry/sentry/issues/48334 and https://docs.flutter.dev/deployment/obfuscate#caveat

Before & after obfuscation and uploading symbol is the Flutter tooling itself, we just report stack traces as it is, if the tooling reports it differently, consider creating a repro case and raising an issue on https://github.com/dart-lang/sdk maybe?
I'll close the issue since the original question is resolved, for the later, if you think it's a sentry's symbolication issue, feel free to raise another one.
