### ISSUE TITLE
how can i define SENTRY_RELEASE custom 

### ISSUE THREAD

**Issue by philos3** [getsentry/sentry-dart-plugin#135]
release  use   name@version from pubspec (string) as default value, but how can i define SENTRY_RELEASE custom ， such as testflight@6.9.2+692 for ios app building,  or googlplay@6.9.2+692  for android app building, or some channel as official@6.9.2+692

as i know ，i can edict yaml manually when building APP for each channel. but I want to know is there any more convenient way to do this

version: 6.9.2+692
SENTRY_RELEASE_IOS: testflight@6.9.2+692
SENTRY_RELEASE_IOS2: appstore@6.9.2+692    
SENTRY_RELEASE: googlplay@6.9.2+692  
SENTRY_RELEASE: official@6.9.2+692

**Comment by philos3** [comment]
It is convenient to define in code,but using sentry-dart-plugin how can i do this in yaml

options.release =
            '${DataUtils.getMarketString()}@${Application.instance.appVersion}+${Application.instance.appBuildNum}';

**Comment by marandaneto** [comment]
You probably need this https://github.com/getsentry/sentry-dart-plugin/issues/81
So you can call the plugin and pass the values as parameters
eg `dart run sentry_dart_plugin --dart-define=release=testflight@6.9.2+692` but we've not implemented this yet.
Your option is editing the YAML directly or setting the env. var. as an alternative.

You can also do `if` conditions and set the `options.release` dynamically depending on if its Android, or iOS.
Closing this in favor of https://github.com/getsentry/sentry-dart-plugin/issues/81

**Comment by eb-so** [comment]
@marandaneto In my codemagic pipline I'm increasing the build number automatically so I need the value of the release to match, are the above solutions works in my case, if so please provide explain a bit how to achieve them

**Comment by marandaneto** [comment]
@eb-so I'm no longer part of the Sentry staff. cc @buenaflor
