### ISSUE TITLE
Sentry could not resolve the “abort” exception,I have uploaded the Debug Symbols Successful (flutter packages pub run sentry_dart_plugin)

### ISSUE THREAD

**Issue by WangQiangQuan** [getsentry/sentry-dart-plugin#136]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm (Rosetta),

### Version

7.7.0

### Steps to Reproduce

Run flutter build apk before executing the sentry_dart_plugin plugin.

refer to: https://docs.sentry.io/platforms/flutter/upload-debug/

### Expected Result

flutter Correct stack

### Actual Result

libc++
+0x04a11c
<unknown>
libc++
+0x04a25c
<unknown>
libc++
+0x04afa0
<unknown>
libc++
+0x04af24
std::terminate
libc++
+0x0a4770
std::__1::thread::~thread
libc
+0x0f9124
__cxa_finalize
libc
+0x0eb4b8
exit
libflutter
+0x63174c
<unknown>
libflutter
+0x633348
<unknown>
libflutter
+0x6eff00
<unknown>
libflutter
+0x6efc94
<unknown>
libapp
+0x317084
_kDartVmSnapshotInstructions
libapp
+0x5a7860
_kDartIsolateSnapshotInstructions
libapp
+0x5a780c
_kDartIsolateSnapshotInstructions
libapp
+0x5a75e4
_kDartIsolateSnapshotInstructions
libapp
+0x868da8
_kDartIsolateSnapshotInstructions
libapp
+0x6b1ebc
_kDartIsolateSnapshotInstructions
libapp
+0x63cf30
_kDartIsolateSnapshotInstructions
libapp
+0x7e53f4
_kDartIsolateSnapshotInstructions
libapp
+0x749254
_kDartIsolateSnapshotInstructions
libapp
+0x7a174c
_kDartIsolateSnapshotInstructions
libapp
+0x447398
_kDartIsolateSnapshotInstructions
libapp
+0x447124
_kDartIsolateSnapshotInstructions
libapp
+0x360bf0
_kDartIsolateSnapshotInstructions
libapp
+0x3607cc
_kDartIsolateSnapshotInstructions
libapp
+0x3606c4
_kDartIsolateSnapshotInstructions
libapp
+0x360208
_kDartIsolateSnapshotInstructions
libapp
+0x4ab680
_kDartIsolateSnapshotInstructions
libapp
+0x4ab56c
_kDartIsolateSnapshotInstructions
libapp
+0x32ffc4
_kDartIsolateSnapshotInstructions
libapp
+0x32fef8
_kDartIsolateSnapshotInstructions
libapp
+0x32fe70
_kDartIsolateSnapshotInstructions
libapp
+0x316d7c
_kDartVmSnapshotInstructions
libflutter
+0x6cbd14
<unknown>
libflutter
+0x804908
<unknown>
libflutter
+0x5a0000
<unknown>
libflutter
+0x5a22ec
<unknown>
libflutter
+0x5ae734
<unknown>
libflutter
+0x3460cc
<unknown>
libflutter
+0x349658
<unknown>
libutils
+0x0181a8
android::Looper::pollInner
libutils
+0x017d1c
android::Looper::pollOnce
libandroid
+0x018598
ALooper_pollOnce
libflutter
+0x349764
<unknown>
libflutter
+0x347d8c
<unknown>
libc
+0x0f55c8
<unknown>
libc
+0x08efbc
<unknown>

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
