### ISSUE TITLE
Support SENTRYCLI_CDNURL env

### ISSUE THREAD

**Issue by fishead** [getsentry/sentry-dart-plugin#150]
It's hard to complete the sentry cli download phase because of internet censorship in China. With the support of SENTRYCLI_CDNURL env, users who can not download directly from Sentry CDN can download from alternative place.

Sentry npm package support this env, link: https://docs.sentry.io/product/cli/installation/#available-installation-options.

I can make a PR about this.

**Comment by buenaflor** [comment]
hi! that would be great if you could prepare a pr :)
