### ISSUE TITLE
Support config sentry cli save directory

### ISSUE THREAD

**Issue by fishead** [getsentry/sentry-dart-plugin#151]
I will run `flutter clean` first to get a clean environment when I build flutter app, but `flutter clean` will remove `.dart_tool` dir, and this plugin store sentry-cli binary in `.dart_tool` dir, so it has to download sentry-cli every time when I build the app.

Support config sentry-cli save directory to store the binary file in a different place to avoid to download it every time.

**Comment by buenaflor** [comment]
Thanks for the issue, I'll be looking into this
