### ISSUE TITLE
`--ignore-missing` doesn't work

### ISSUE THREAD

**Issue by feinstein** [getsentry/sentry-dart-plugin#153]
I got an error at the end of the upload saying:

```
error: Could not find the SHA of the previous release in the git history. If you limit the clone depth, try to increase it. Otherwise, it means that the commit we are looking for was amended or squashed and cannot be retrieved. Use --ignore-missing flag to skip it and create a new release with the default commits count.

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

exitCode: 1
```

So then I added the `--ignore-missing` flag and run `dart run sentry_dart_plugin --ignore-missing`, but then I continue to get the same error.

The commit was squashed.

**Comment by feinstein** [comment]
Just a little bit more info, I develop new features into a branch and then I squash and merge this branch into the development branch.  So I think I uploaded the debug symbols in a feature branch (the feature was to add sentry and test sentry debug symbols upload), and later when I merge/squased this branch I can't upload the symbols without seeing an error.

**Comment by mattsolle** [comment]
Any update? This is effecting our application's CI/CD pipeline for production.

**Comment by brightknight08** [comment]
happening to my projects too.

**Comment by denrase** [comment]
We are looking into this now, thank you for reporting this.

**Comment by denrase** [comment]
@feinstein Just a question, does it work as expected when you add `ignore_missing: true` to the yaml config?

**Comment by denrase** [comment]
This is probably an error message from `sentry-cli`, which we are using/wrapping. Everything in the dart plugin should be configured via the yaml config and not by command line parameters.

**Comment by feinstein** [comment]
It does work when I add it to the yaml file.

This limitation would be useful to be added into the docs.

**Comment by denrase** [comment]
@feinstein Yes, It's not ideal that the error references a solution that does not work for the plugin, but rather for the underlying component we are using. Only adds confusion.

@mattsolle @brightknight08 Please also check if adding `ignore_missing: true` to your configuration to see if this resolves your issue.

**Comment by denrase** [comment]
@feinstein We have updated our troubleshooting section.

**Comment by feinstein** [comment]
Great, thanks a lot!
