### ISSUE TITLE
414 Request-URI Too Large bug solved on 2.20.0 sentry-cli

### ISSUE THREAD

**Issue by hazzo** [getsentry/sentry-dart-plugin#155]
### Environment

sentry-dart-plugin v1.5.0

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.6, on macOS 13.3 22E252 darwin-arm64, locale en-ES)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/guido/fvm/versions/3.10.6. Consider adding /Users/guido/fvm/versions/3.10.6/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (2 available)
    ! Error: Guido’s iPhone is busy: Waiting to connect and unlock the device. Xcode will continue when Guido’s iPhone is finished. (code -10)
[✓] Network resources
```

### Steps to Reproduce

1. flutter run build
2. flutter packages pub run sentry_dart_plugin

### Expected Result

Upload source maps without error

### Actual Result

Sentry it's responding with a 414 error. Due to this bug in sentry-cli https://github.com/getsentry/sentry-cli/issues/1657 that was solved with this PR https://github.com/getsentry/sentry-cli/pull/1680 that landend on `sentry-cli 2.20.0` and this plugin uses `2.19.4`

Please bump the version to last sentry-cli version.

**Comment by buenaflor** [comment]
The plugin is now on version 1.6.0 which uses cli 2.20.6. let us know if you have any further questions!

**Comment by poster983** [comment]
I am on sentry-cli version 2.21.1 and am getting the same issue, although it worked last week. Is there a workaround?
