### ISSUE TITLE
Support for on-premise Sentry server

### ISSUE THREAD

**Issue by Amir-P** [getsentry/sentry-dart-plugin#16]
Currently it's not possible to use this plugin with on-premise Sentry servers due to lack of url configuration.

**Comment by philipphofmann** [comment]
@Amir-P, why did you close this issue? Did we solve this @marandaneto?

**Comment by Amir-P** [comment]
> @Amir-P, why did you close this issue? Did we solve this @marandaneto?

I closed it since #17 got merged. Check that out. @philipphofmann
