### ISSUE TITLE
Fix ubuntu integration tests

### ISSUE THREAD

**Issue by buenaflor** [getsentry/sentry-dart-plugin#161]
most likely culprit: GH runner version or image version.

rerunning old successful runs will lead to failed runs

Old successful runs, [example](https://github.com/getsentry/sentry-dart-plugin/actions/runs/6107445549/job/16574455112):
```shell
Current runner version: '2.308.0'
Operating System
Runner Image
  Image: ubuntu-22.04
  Version: 20230821.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230821.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230821.1
Runner Image Provisioner
  2.0.266.1
  ```
  
New failed runs, [example](https://github.com/getsentry/sentry-dart-plugin/actions/runs/6235735808/job/16938838783):
```shell
Current runner version: '2.309.0'
Operating System
Runner Image
  Image: ubuntu-22.04
  Version: 20230911.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230[9](https://github.com/getsentry/sentry-dart-plugin/actions/runs/6235755273/job/16925619627#step:1:10)11.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230911.1
Runner Image Provisioner
  2.0.310.1
  ```

**Comment by denrase** [comment]
Observations

Endpoint: http://127.0.0.1:8000/api/0/projects/sentry-sdks/sentry-dart-plugin/files/difs/assemble/
- Both runs find the same number of files
- Both runs have the same dependencies (os, flutter, sentry-cli). 
- In the success run there are three `app.so` files and three `libapp.so` files
- In the failure run there are six `libapp.so` files
- The debug id's are duplicated in both, maybe leading to some file name mixup in 'sentry-cli'?
- In both runs the `app.so` files should be present present, as they are in later failing runs.

Success
https://github.com/getsentry/sentry-dart-plugin/actions/runs/6140635136/job/16659855989

```json
"99b099dff41a4414b5470f785fa17a03a7405fdb":
{
    "name": "app.so",
    "debug_id": "6ff64056-0e28-15fa-c26e-f1715b2a12e9",
    "chunks":
    [
        "99b099dff41a4414b5470f785fa17a03a7405fdb"
    ]
},

"0c2b6f3c6cab12796e3d6f9aecc3441b463f783f":
{
    "name": "libapp.so",
    "debug_id": "6ff64056-0e28-15fa-c26e-f1715b2a12e9",
    "chunks":
    [
        "0c2b6f3c6cab12796e3d6f9aecc3441b463f783f"
    ]
}
```

Failure
https://github.com/getsentry/sentry-dart-plugin/actions/runs/6221053336/job/16882288167

```json
"24c3b00e5b6811db190936099c7fc95da596ec30":
{
    "name": "libapp.so",
    "debug_id": "4bb27947-4dbf-7b34-f9d1-a6dc80569693",
    "chunks":
    [
        "24c3b00e5b6811db190936099c7fc95da596ec30"
    ]
},
"06e33d5d773778ab9f55f44b9aaf37ed32f7c41b":
{
    "name": "libapp.so",
    "debug_id": "4bb27947-4dbf-7b34-f9d1-a6dc80569693",
    "chunks":
    [
        "06e33d5d773778ab9f55f44b9aaf37ed32f7c41b"
    ]
},
```

<img width="383" alt="Bildschirmfoto 2023-09-20 um 10 53 55" src="https://github.com/getsentry/sentry-dart-plugin/assets/3984453/e6d51e5a-f86d-4e54-b43d-7fd8fbeb3f10">
<img width="422" alt="Bildschirmfoto 2023-09-20 um 10 53 58" src="https://github.com/getsentry/sentry-dart-plugin/assets/3984453/437c19ff-571f-4c70-836c-a876d8658371">

<img width="912" alt="Bildschirmfoto 2023-09-20 um 10 16 00" src="https://github.com/getsentry/sentry-dart-plugin/assets/3984453/aeacca2d-b47a-47aa-9922-141401542421">

**Comment by denrase** [comment]
So the file names that `sentry-cli` is posting to our local server are missing the three `app.so` files, but have three `libapp.so` files too many, possibly because they have the same `debug_id` assigned? This is only failing on ubuntu and has started recently. Do you have some feedback/ideas on this @krystofwoldrich @kamilogorek @loewenheim @kamilogorek?

**Comment by denrase** [comment]
Here's the closed PR, showing that it was not the flutter version: #162
