### ISSUE TITLE
error: Two different url values supplied

### ISSUE THREAD

**Issue by eb-so** [getsentry/sentry-dart-plugin#181]
### Environment

What version are you running? Etc.
`sentry_flutter: 7.8.0`
`sentry_dart_plugin: 1.6.3`

and here are my build configs
```
sentry:
  upload_debug_symbols: true
  upload_source_maps: false
  upload_sources: false
  project: my-app
  org: myorg
  log_level: error
```  
### Steps to Reproduce

I'm trying to upload the debug symbols to Sentry using sentry_dart_plugin
but I'm having this error when I try to do `flutter packages pub run sentry_dart_plugin`
I'm providing the SENTRY_URL and SENTRY_AUTH_TOKEN using dart define

### Expected Result

The debug symbols to be uploaded

### Actual Result

[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 0% reading config values..        
Downloading sentry-cli from https://downloads.sentry-cdn.com/sentry-cli/2.21.2/sentry-cli-Darwin-universal to .dart_tool/pub/bin/sentry_dart_plugin/sentry-cli

Downloaded Sentry CLI binary checksum verification passed successfully (hash: *********dde7d62fc54ab33df).

Sentry CLI downloaded successfully.

☑ reading config values                                                             

[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 9% validating config values..                             
☑ validating config values                                                             

[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 18% uploading debug symbols..                                
includeSources is disabled, not uploading sources.

error: Two different url values supplied: `https://sentry.io` (from token), `https://**********.sentry.io/projects/**********-app/?project=45**********`.

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

exitCode: 1

@vaind is this related to [173](https://github.com/getsentry/sentry-dart-plugin/issues/173)

**Comment by vaind** [comment]
@eb-so no, to me that doesn't look related at all.

You seem to have some kind of configuration issue

**Comment by eb-so** [comment]
@vaind I don't know if it's related to the issue but I'm running this on codemagic pipline

**Comment by buenaflor** [comment]
You don't need to use `SENTRY_URL` if you're not on self-hosted, which I assume you don't since you use `https://sentry.io` as URL

**Comment by buenaflor** [comment]
releases are automatically generated. currently there's not option to disable it but you can [manually upload](https://docs.sentry.io/platforms/flutter/upload-debug/?original_referrer=https%3A%2F%2Fwww.google.com%2F#manually-upload-debug-symbols) the symbols to customize it to your needs.

**Comment by eb-so** [comment]
Thank you
