### ISSUE TITLE
sentry reported an error: request failure (http status: 500)

### ISSUE THREAD

**Issue by jacjac11** [getsentry/sentry-dart-plugin#190]
### Environment

7.14.0

### Steps to Reproduce

What you did?
flutter packages pub run sentry_dart_plugin
### Expected Result
Debug symbols should be uploaded.

What you thought would happen?

### Actual Result
Upload failed.

### Logs
flutter packages pub run sentry_dart_plugin
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 0% reading config values..        
Downloading sentry-cli from https://downloads.sentry-cdn.com/sentry-cli/2.21.2/sentry-cli-Darwin-universal to .dart_tool/pub/bin/sentry_dart_plugin/sentry-cli
Downloaded Sentry CLI binary checksum verification passed successfully (hash: xx).
Sentry CLI downloaded successfully.
☑ reading config values                                                             
☑ validating config values                                                             
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 18% uploading debug symbols..                                
includeSources is disabled, not uploading sources.
> Found 226 debug information files
> Prepared debug information files for upload
error: API request failed
  caused by: sentry reported an error: internal server error (http status: 500)
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

**Comment by buenaflor** [comment]
Hi, just tried it and it works. 

What's your geographical location? We recently had some issues with requests being blocked in China.
