### ISSUE TITLE
Flutter 3.19.0, versions problem

### ISSUE THREAD

**Issue by marcinkaczmarzyk** [getsentry/sentry-dart-plugin#201]
### Environment

 Flutter (Channel stable, 3.19.0, on macOS 14.3.1 23D60 darwin-arm64, locale pl-PL)
 sentry_dart_plugin: ^1.7.0
 integration_test:
    sdk: flutter
### Steps to Reproduce

Try to install sentry dart plugin with integration_test flutter package on the latest flutter version 3.19.0

### Expected Result

That should work

### Actual Result

Because no versions of sentry_dart_plugin match >1.7.0 <2.0.0 and sentry_dart_plugin 1.7.0 depends on process ^4.2.4, sentry_dart_plugin ^1.7.0 requires process ^4.2.4.
And because no versions of process match >4.2.4 <5.0.0, sentry_dart_plugin ^1.7.0 requires process 4.2.4.
And because process 4.2.4 depends on file ^6.0.0 and every version of integration_test from sdk depends on file 7.0.0, sentry_dart_plugin ^1.7.0 is incompatible with integration_test from sdk.
So, because XXX depends on both integration_test from sdk and sentry_dart_plugin ^1.7.0, version solving failed.

**Comment by buenaflor** [comment]
hey thanks for the issue.

while we ship a fix you can work around this with overriding the dependency for now

```
dependency_overrides:
  process: ^5.0.0
```

**Comment by buenaflor** [comment]
this is now part of [1.7.1](https://github.com/getsentry/sentry-dart-plugin/releases/tag/1.7.1)
