### ISSUE TITLE
Add config param to set url prefix

### ISSUE THREAD

**Issue by jblankenship5** [getsentry/sentry-dart-plugin#204]
In the CLI when uploading source maps I can specify the URL prefix if my apps assets live at a different address. Please add the same functionality for this package.

I.E. My app lives at example.com/app instead of example.com. When the errors are reported in sentry after using this plugin it cannot find the files it's looking for online because it's looking at example.com/main.dart.js.map instead of example.com/app/main.dart.js.map.

See https://docs.sentry.io/product/cli/releases/#sentry-cli-sourcemaps

**Comment by buenaflor** [comment]
Implemented in https://github.com/getsentry/sentry-dart-plugin/pull/253
