### ISSUE TITLE
`SENTRY_DIST` env. variable doesn't work

### ISSUE THREAD

**Issue by feinstein** [getsentry/sentry-dart-plugin#210]
### Environment

1.7.1

### Steps to Reproduce

I have the following script:

```bash
SENTRY_DIST=$BUILD_NUMBER
echo "Sentry distribution number: $SENTRY_DIST"
dart run sentry_dart_plugin
```

this prints:

```console
Sentry distribution number: 14
```

But after the `sentry_dart_plugin` runs I see this:

```console
Created release my_app@0.0.1+1
```

So it doesn't seem to me that `SENTRY_DIST` is being used by the CLI, as I am expecting to see `my_app@0.0.1+14`.

**Comment by buenaflor** [comment]
Hi!

just a sanity check, you didn't set up `dist` in pubspec or sentry.properties?

**Comment by feinstein** [comment]
I didn't, but I have the version set-up in pubspec.yaml, but I override the build number in my CICD script, as a flag for the Flutter build tool

**Comment by denrase** [comment]
Just checked AFAIK we explicitly added a test that the build number from release is used as `dist`:

https://github.com/getsentry/sentry-dart-plugin/blob/eaa78be78554111a6829b70cd33b58ec983f0a3c/test/plugin_test.dart#L141

So this seems to be expected behaviour, but I can't tell what the reasoning behind this was.

Are you providing `release` with build number? It has precedence over the `versions` build number.

**Comment by feinstein** [comment]
This doesn't make sense to me, pubspec.yaml versions are the expected way to define versions, so all other methods are used to override that one.

The Flutter tool has flags to override pubspec.yaml, and so should your environment variable do.

It's common for CICDs to automatically generate a build number and no one wants to change the pubspec.yaml from a CICD bash script to inject the distribution number.

**Comment by feinstein** [comment]
I think this issue still persists. I am using version 2.1.0 and I got this output:

>☑ uploading debug symbols                                                             
>
>Created release my_app@0.0.1+1

But my command was

>SENTRY_DIST=$APP_BUILD_NUMBER
>echo "Sentry distribution number: $SENTRY_DIST"
>dart run sentry_dart_plugin

Where `APP_BUILD_NUMBER` was 4, which was confirmed by the `echo` as:

>Sentry distribution number: 4

**Comment by buenaflor** [comment]
hm I could not reproduce this, it works on my local build

```yaml
# in my pubspec.yaml
version: 1.0.0+1
```

```shell
export SENTRY_DIST=4
```

running the dart plugin leads to `Created release flutter_sentry_test@1.0.0+4`


can you share your full plugin configuration?

**Comment by feinstein** [comment]
Can you try with a Squash commit where the plugin doesn't find the previous commit?

**Comment by buenaflor** [comment]
not sure how the commits are linked to dist not being set correctly, afaik the commits are only used to associate to certain releases

**Comment by feinstein** [comment]
>can you share your full plugin configuration?

Is this what you are asking for?

```yaml
sentry:
  project: my_project
  org: my_org
```

My CICD runs this: `dart run sentry_dart_plugin`

**Comment by feinstein** [comment]
@buenaflor it was my mistake sorry, I forgot to use `export` to make the env variable available to the child process
