### ISSUE TITLE
Allow to set cliPath via options

### ISSUE THREAD

**Issue by beatstream69** [getsentry/sentry-dart-plugin#220]
We are building flutter apps in a Docker container with preinstalled sentry-cli.

Please allow to set up sentry-cli path from configuration to speed up building and reduce unnecessary network usage.

Also I think that preinstalled binary must be used first and then fallback to downloading.

**Comment by beatstream69** [comment]
Oh I see..
https://github.com/getsentry/sentry-dart-plugin/pull/214

**Comment by beatstream69** [comment]
No, it`s another issue and another solution, so reopened =)

**Comment by buenaflor** [comment]
Thx for the issue! We'll take a look
