### ISSUE TITLE
override buildFilesFolder via arguments

### ISSUE THREAD

**Issue by sobimor** [getsentry/sentry-dart-plugin#228]
we need to set custom buildFilesFolder (working dir) so sentry-cli starts searching for debug symbols in that directory.
Just like other properties, it would be awesome to be able to set custom `buildFilesFolder`

Unfortunately, this lack led us to use `sentry-cli` directly because it is capable of setting path.

**Comment by buenaflor** [comment]
hey, should be a good addition.

quick question: where do you store the debug syms? I assume they'd not be in a build folder within the projects dir otherwise the plugin would be able to locate them?

**Comment by sobimor** [comment]
We store it in the dist/sym directory.
The problem is when sentry_cli tries to find all symbols in our project, it finds more than 600 files which is wrong(because searches for symbols in the root dir and checks every folder).

**Comment by sobimor** [comment]
> hey, should be a good addition.
> 
> quick question: where do you store the debug syms? I assume they'd not be in a build folder within the projects dir otherwise the plugin would be able to locate them?
We store it in the dist/sym directory.
The problem is when sentry_cli tries to find all symbols in our project, it finds more than 600 files which is wrong(because searches for symbols in the root dir and checks every folder).

**Comment by buenaflor** [comment]
Got it, thanks for raising this, we'll take a look
