### ISSUE TITLE
[Flutter Web] Unable to define SENTRY_AUTH_TOKEN via --dart-define

### ISSUE THREAD

**Issue by IvanDeluxe** [getsentry/sentry-dart-plugin#23]
### Environment

Flutter Web

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Flutter 2.8.1, sentry_dart_plugin: ^1.0.0-beta.1

### Steps to Reproduce

In pubspec.yaml:
```
sentry:
  project: projectname
  org: orgname
```

In terminal:
```
flutter build web --dart-define SENTRY_AUTH_TOKEN=64CHARLONGSTR
flutter pub run sentry_dart_plugin
```

### Expected Result

I expected it to work :D

### Actual Result
```
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 0% reading config values..
sentry-cli is not available under the assets folder, using pre-installed sentry-cli
☑ reading config values
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 9% validating config values..
Auth Token is empty, check 'auth_token' at pubspec.yaml or SENTRY_AUTH_TOKEN env. var.
pub finished with exit code 1
```

Did I do something wrong?

 Thanks!

**Comment by IvanDeluxe** [comment]
I'll just add - everything works if I put `auth_token: 64CHARLONGSTR` in pubspec.yaml, but I don't want to commit that token.

**Comment by marandaneto** [comment]
this plugin does not support `--dart-define` yet, only environmental variables

**Comment by marandaneto** [comment]
We'd just need to add support for it using https://api.flutter.dev/flutter/dart-core/String/String.fromEnvironment.html on https://github.com/getsentry/sentry-dart-plugin/blob/main/lib/src/configuration.dart#L106-L114

**Comment by devxpy** [comment]
Shouldn't this plugin support reading the token from the `.sentrycli` file (mine was generated by `sentry-cli`)?

**Comment by marandaneto** [comment]
> Shouldn't this plugin support reading the token from the `.sentrycli` file (mine was generated by `sentry-cli`)?

This plugin uses sentry-cli underneath so it should, but the `~/.sentryclirc` file is for a global configuration, and this plugin allows a configuration per-project basis.
You're free to use `sentry-cli` and the `.sentryclirc` file directly tho, the plugin just makes it easier for Dart/Flutter projects.

**Comment by devxpy** [comment]
> > Shouldn't this plugin support reading the token from the `.sentrycli` file (mine was generated by `sentry-cli`)?
> 
> This plugin uses sentry-cli underneath so it should, but the `~/.sentryclirc` file is for a global configuration, and this plugin allows a configuration per-project basis. You're free to use `sentry-cli` and the `.sentryclirc` file directly tho, the plugin just makes it easier for Dart/Flutter projects.

Makes sense, I jut felt like it was a bit hard to specify the auth token. 

Adding it in the pubspec.yaml seems like a security issue, 
and adding it to my shell environment vars means I cant use it with multiple projects.

`sentry-cli` seems to read the `.sentryclirc` from the current directory, so I can set that up for every project individually without having to commit the auth token to git.

**Comment by marandaneto** [comment]
Yes, I agree.
That's why this issue is about adding support to `--dart-define` which could be passed at compilation time, so it's not a global configuration.

**Comment by Overman775** [comment]
+1

**Comment by chathu-novade** [comment]
Just add the SENTRY_AUTH_TOKEN as a env variable. It's easy to setup with CI

**Comment by ben-xD** [comment]
From my understanding, `SENTRY_AUTH_TOKEN` shouldn't be passed to `--dart-define` because it's not an environment variable for your application, but the **the CLI**. Your application uses different credentials, `SENTRY_DSN`.

**Comment by marandaneto** [comment]
The SDK already supports `SENTRY_DSN` via `--dart-define`.
Passing `SENTRY_AUTH_TOKEN` to `flutter build web` won't make sense, because the Dart Plugin uses the token and not the SDK.
You can already set the token via pub config or env. var.
