### ISSUE TITLE
Dependencies issues.

### ISSUE THREAD

**Issue by Geyom** [getsentry/sentry-dart-plugin#244]
### Environment

flutter: 3.22
sentry_dart_plugin: ^2.0.0

I am using this commit 
` sentry_dart_plugin:
    git:
      url: https://github.com/getsentry/sentry-dart-plugin
      ref: 608bc1c` 

I am using another package to handle websocket: web_socket_channel

### Steps to Reproduce

1. Create a raw flutter app
2. Add dependencies:
`sentry_dart_plugin: ^2.0.0
web_socket_channel: ^3.0.0`
3. Run flutter pub get

### Expected Result

Should install dependencies without issue.

### Actual Result

The install ends up by prompting:

The current Dart SDK version is 3.4.1.

Because test >=1.16.0-nullsafety.8 <1.16.3 depends on web_socket_channel ^1.0.0 and test >=0.12.0-beta.3 <1.16.0-nullsafety.8 doesn't support null safety, test >=0.12.0-beta.3 <1.16.3 requires web_socket_channel ^1.0.0.
And because test >=1.16.3 <1.16.6 depends on web_socket_channel >=1.0.0 <3.0.0 and test >=1.16.6 <1.25.5 depends on web_socket_channel ^2.0.0, test >=0.12.0-beta.3 <1.25.5 requires web_socket_channel >=1.0.0 <3.0.0.
And because test >=1.25.3 <1.25.6 depends on test_api 0.7.1 and test >=1.25.6 depends on test_api 0.7.2, test >=0.12.0-beta.3 requires test_api 0.7.1 or 0.7.2 or web_socket_channel >=1.0.0 <3.0.0.
And because every version of flutter_test from sdk depends on test_api 0.7.0 and properties >=2.0.0 depends on test ^1.0.0, if flutter_test from sdk and properties >=2.0.0 then web_socket_channel >=1.0.0 <3.0.0.
And because every version of sentry_dart_plugin from git depends on properties ^2.1.0 and whyonearth depends on web_socket_channel ^3.0.0, flutter_test from sdk is incompatible with sentry_dart_plugin from git.
So, because whyonearth depends on both sentry_dart_plugin from git and flutter_test from sdk, version solving failed.

The lower bound of "sdk: '>=1.8.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety

### Problem investigation

The problem is coming from the properties package you use as dependency.

In their pubspec.yaml under dependencies they put :
`test: ^1.0.0`

I think it should have been put under dev_dependencies.

**Comment by Geyom** [comment]
Thanks for your answer.
Your quick fix will do for the moment 👍

**Comment by vaind** [comment]
should be fixed with the new release of https://pub.dev/packages/properties/changelog
