### ISSUE TITLE
sentry_dart_plugin default release version

### ISSUE THREAD

**Issue by ekuleshov** [getsentry/sentry-dart-plugin#250]
### Environment

sentry_dart_plugin: 2.1.0

### Steps to Reproduce

1. run `flutter packages pub run sentry_dart_plugin`
2. observe release uploaded to the Sentry web UI

### Expected Result

The plugin [docs says the release is constructed from the pubspec](https://pub.dev/packages/sentry_dart_plugin#release), so I'd expect release look like `buildName+buildNumber`.

My Sentry initialization sets release at runtime to `buildName+buildNumber` (matching with pubspec as it should be) and because of that uploaded symbols are not linked/not used with issues and I have two sets of releases shown in Sentry web UI.

### Actual Result

The release is shown as `buildName (buildNumber)`.

**Comment by buenaflor** [comment]
> My Sentry initialization sets release at runtime to buildName+buildNumber

you mean the release set by default through `SentryFlutter.init`?

**Comment by ekuleshov** [comment]
> you mean the release set by default through `SentryFlutter.init`?

That is correct

**Comment by buenaflor** [comment]
@denrase could you have a look pls

**Comment by denrase** [comment]
@ekuleshov Could you sahre the code with us where you set `buildName+buildNumber`? If the values from pubspec.yaml are the ones you want, you do not have to set this explicitly in options setup.

**Comment by ekuleshov** [comment]
I'm using the `package_info_plus` to get the version info:

```
      PackageInfo pi = await PackageInfo.fromPlatform();
      _appVersion = '${pi.version}+${pi.buildNumber}';
```

> [@ekuleshov](https://github.com/ekuleshov) Could you sahre the code with us where you set `buildName+buildNumber`? If the values from pubspec.yaml are the ones you want, you do not have to set this explicitly in options setup.

I would hope so, but uploaded artifacts wasn't linked with the app release. I've hacked it around in pubspec.yaml like this for now, but this shouldn't be required.

```
version: &ver 2.0.7+32
...
sentry:
  ...
  release: *ver
  ...
```

**Comment by denrase** [comment]
Thx, i'll try to reproduce this.

**Comment by buenaflor** [comment]
let us know if this is still an issue
