### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by Tosuj-work** [getsentry/sentry-dart-plugin#262]
### Environment

What version are you running? Etc.
2.1.0

### Steps to Reproduce
flutter build apk --release --split-debug-info --obfuscate -t ./lib/main_prod.dart
flutter packages pub run sentry_dart_plugin

### Expected Result
success uploading

What you thought would happen.
error uploading

### Actual Result

logfile
[log.txt](https://github.com/user-attachments/files/17073667/log.txt)

**Comment by buenaflor** [comment]
hi, does this only on android or also when uploading dsyms for ios?

**Comment by Tosuj-work** [comment]
> hi, does this happen only on android or also when uploading dsyms for ios?

hi, ios is not in production yet and has not been tried there, so now it is only on android

**Comment by buenaflor** [comment]
@Tosuj-work are you running sentry self hosted?

**Comment by buenaflor** [comment]
@szokeasaurusrex have you seen this error before in the sentry-cli? any clues?

**Comment by Tosuj-work** [comment]
Hi! we have updated self hosted sentry to the latest version and the bug has been fixed. Everything is working now
