### ISSUE TITLE
Vulnerability of keeping sentry.properties file in the app bundle

### ISSUE THREAD

**Issue by nrajput05** [getsentry/sentry-dart-plugin#280]
Since I am placing sentry.properties file in the root of flutter project and it will be a part of my build how vulnerable is it to keep the auth_token in it?

**Comment by vaind** [comment]
> Since I am placing sentry.properties file in the root of flutter project and it will be a part of my build how vulnerable is it to keep the auth_token in it?

When you create the token, you're assigning permissions to it. Then when you share it (by writing it in a file) and who you share it with, you have to assume they now have the same permissions.

Normally in shared/non-private projects, you'd use environment variables for tokens, namely `SENTRY_AUTH_TOKEN` in this case.

**Comment by nrajput05** [comment]
> > Since I am placing sentry.properties file in the root of flutter project and it will be a part of my build how vulnerable is it to keep the auth_token in it?
> 
> When you create the token, you're assigning permissions to it. Then when you share it (by writing it in a file) and who you share it with, you have to assume they now have the same permissions.
> 
> Normally in shared/non-private projects, you'd use environment variables for tokens, namely `SENTRY_AUTH_TOKEN` in this case.

Yes that's fine by me if any colleague working with my code is looking at the sentry.properties file. My ask what happens was after deployment to web/iOS/android. Is this .properties file visible when some outside get their hands on the ipa/apk/web-assets and they somehow extract the minified/obfuscated code?
