### ISSUE TITLE
Sentry dart plugin does not detect and send .dart files to Sentry.

### ISSUE THREAD

**Issue by lukaszmielczarekdev** [getsentry/sentry-dart-plugin#283]
### Environment

Sentry dart plugin  v.2.2.0

### Steps to Reproduce

The problem I have is that it doesn't send .dart files to Sentry, it only sends one package with .js files (10 pieces). There should be a second portion, much larger with .dart files. The logs say that it found 10 files first, then 0. In the previous version of the package, all files were sent, and in the latest one only one part.

![Image](https://github.com/user-attachments/assets/885cc84c-7105-44b8-b16d-abea26cb7d48)

### Expected Result
![Image](https://github.com/user-attachments/assets/f97893df-160c-44ea-8826-c1b51bbe32b6)

### Actual Result
![Image](https://github.com/user-attachments/assets/e50b45e0-f8f5-419a-acbb-fda5de62dfd7)

**Comment by buenaflor** [comment]
thx for the info, with `2.1.0` it worked before?

**Comment by buenaflor** [comment]
We bumped our CLI from v2.27.0 to v2.38.1 in 2.2.0, could you try setting `sentry_cli_version` to `2.27.0` in your plugin config and see if that makes a difference?

**Comment by lukaszmielczarekdev** [comment]
Still doesn't work.

**Comment by lukaszmielczarekdev** [comment]
Still doesn't work.
I have a Flutter app that is embedded in a React app when built. 
I use `fvm flutter build web --base-href "/simulator/" --source-maps --output "../shopify/web/frontend/simulator" --dart-define=SENTRY_RELEASE="${RELEASE_NAME}" --dart-define=SENTRY_DIST="${DIST_ID}"`.
Maybe this information will be useful.

**Comment by lukaszmielczarekdev** [comment]
UPDATE: I changed the build_path to a few folders up and now the .dart files are uploaded and working 😉

**Comment by vaind** [comment]
@lukaszmielczarekdev could you post your updated config? I'd like to understand what's going on (I've made the PR to change what we upload)

**Comment by ciprig** [comment]
In 2.1.0 the **web_build_path** was a full path _build/web_ and now in 2.2.0 is relatively just _web_ making existing configurations. We have changed to use the defaults and still, sentry reports that there is _nothing to upload_ for web builds

**Comment by vaind** [comment]
@lukaszmielczarekdev @ciprig this issue should be fixed by #285 

You can verify or use the fix in the meantime by adding a dependency override:

```yaml
  sentry_dart_plugin:
    git:
      url: https://github.com/getsentry/sentry-dart-plugin.git
      ref: efa59dda844c34c6399bc09ae9fa27f0fd9daa27
```

**Comment by buenaflor** [comment]
official fix is released in `2.2.1`

**Comment by bizz84** [comment]
I'm still running into this issue. My setup:

```yaml
dev_dependencies:
  sentry_dart_plugin: ^2.2.1

# Sentry Dart Plugin
sentry:
  upload_debug_symbols: true
  upload_source_maps: false
  upload_sources: false
  project: flutter-tips-app
  org: andrea-bizzotto
  wait_for_processing: true
  log_level: error # possible values: trace, debug, info, warn, error
  commits: auto
  ignore_missing: true
  symbols_path: build
```

Run commands:

```
flutter build web -t lib/main_prod.dart --dart-define=WEB_FLAVOR=prod --dart-define-from-file=.env.prod --base-href / --release --source-maps

dart run sentry_dart_plugin --sentry-define=upload_source_maps=true --sentry-define=upload_sources=true
```

Report:

```
Source Map Upload Report
  Scripts
    ~/assets/packages/mixpanel_flutter/assets/mixpanel.js (sourcemap at ../../../../main.dart.js.map)
    ~/canvaskit/canvaskit.js (sourcemap at ../main.dart.js.map)
    ~/canvaskit/chromium/canvaskit.js (sourcemap at ../../main.dart.js.map)
    ~/canvaskit/skwasm.js (sourcemap at ../main.dart.js.map)
    ~/canvaskit/skwasm.worker.js (sourcemap at ../main.dart.js.map)
    ~/drift_worker.js (sourcemap at main.dart.js.map)
    ~/flutter.js (sourcemap at flutter.js.map)
    ~/flutter_bootstrap.js (sourcemap at flutter.js.map)
    ~/flutter_service_worker.js (sourcemap at main.dart.js.map)
    ~/main.dart.js (sourcemap at main.dart.js.map)
  Source Maps
    ~/main.dart.js.map

> Found 86 files

> Analyzing 86 sources

> Rewriting sources

> Adding source map references

> Bundled 86 files for upload
> Bundle ID: 70e520bb-70e7-5d33-ba70-f5795bf1ccbb

> Uploaded files to Sentry

> File processing complete
> Organization: andrea-bizzotto
> Project: flutter-tips-app
> Release: flutter_tips_and_tricks_app@1.3.1+57
> Dist: 57
> Upload type: artifact bundle

Source Map Upload Report
  Scripts
    ~/app_routes.dart (no sourcemap ref)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/app_routes.dart)
    ~/firebase_options_dev.dart (no sourcemap ref)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/firebase_options_dev.dart)

~/firebase_options_prod.dart (no sourcemap ref)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/firebase_options_prod.dart)
... and so on
```

Any ideas what could be wrong?

**Comment by buenaflor** [comment]
cc @denrase could you have a look here pls

**Comment by buenaflor** [comment]
@otopba which plugin version are you using?

**Comment by otopba** [comment]
> [@otopba](https://github.com/otopba) which plugin version are you using?

sentry_dart_plugin: ^2.4.0

**Comment by otopba** [comment]
> [@otopba](https://github.com/otopba) could you create another issue please with steps to reproduce, and the platforms it affects etc..

Sure. Done https://github.com/getsentry/sentry-dart-plugin/issues/302
