### ISSUE TITLE
Source Maps does not works with Flutter Web

### ISSUE THREAD

**Issue by chathu-novade** [getsentry/sentry-dart-plugin#38]
### Environment

Flutter SDK version

` "flutterSdkVersion": "3.0.5"`

sentry_dart_plugin version:  

`sentry_dart_plugin: ^1.0.0-beta.1`

```bash
stdout: > Found 3631 release files
> Analyzing 3631 sources
> Rewriting sources
> Adding source map references
> Bundled 3631 files for upload
> Uploaded release files to Sentry
> File upload complete (processing pending on server)
> Organization: novade
> Project: novade
> Release: novade_lite@1.7.0+63
> Dist: 63
```

### Steps to Reproduce

1. Build the project for web.
2. Setup pubspec config as following
```yaml
sentry:
  upload_source_maps: true

```
3. Run `flutter flutter packages pub run sentry_dart_plugin`

### Expected Result

We were using sentry-cli to upload source map previously and it also didn't work. We were asked to try this new plugin and seem it also doesn't work.

<img width="1073" alt="Screenshot 2022-08-29 at 3 41 22 PM" src="https://user-images.githubusercontent.com/107825037/187178842-e08344a9-c18b-4cb0-af8c-25e992643cb9.png">

### Actual Result

Source maps should setup correctly.

**Comment by marandaneto** [comment]
@chathu-novade The screenshot is about the source maps of the Dart SDK itself and not your App's code.
Do you see your App's code symbolicated? that should work OOTB.

**Comment by chathu-novade** [comment]
This is what the stack looks like. Can not see the anything related to app code.
<img width="1085" alt="Screenshot 2022-08-30 at 1 16 48 PM" src="https://user-images.githubusercontent.com/107825037/187380498-b4738c19-e465-40dc-a635-e859a2959db6.png">

**Comment by chathu-novade** [comment]
The hidden source section of the screenshot looks like the following.

```
source: https://domain.tld/hostedtoolcache/Flutter/3.0.5/macos/flutter/.pub-cache/hosted/pub.dartlang.org/sentry-6.9.1/lib/src/sentry_client.dart

**Comment by marandaneto** [comment]
I don't follow, the screenshot below has the symbolicated stack trace, it's not minified, what's the problem you are having? can you please update the issue description with more details?

**Comment by chathu-novade** [comment]
@marandaneto I can not see any stack trace related my my dart code in the flutter project. It show only minified:e4b and exception but not the line of dart code.

**Comment by marandaneto** [comment]
@chathu-novade can you provide the code snippet of the Sentry SDK init?
Can you provide the full config of the `sentry` plugin?
Can you provide the command line you are using to build your Flutter app?

**Comment by chathu-novade** [comment]
Sentry SDK init

```dart
 await SentryFlutter.init(
      (options) {
        options
          ..environment = env.toStr()
          ..release = sentryRelease // from String.fromEnvironment('SENTRY_RELEASE')
          ..dsn = dsn;
      },
      // Init your App.
      appRunner: () => runApp(const _App()),
    );
```

Sentry plugin config

```yaml
sentry:
  upload_source_maps: true
```

Flutter build command

```bash
flutter build web --dart-define=SENTRY_RELEASE=$(SENTRY_RELEASE) --dart-define=AMPLITUDE_API_KEY=$(AMPLITUDE_API_KEY) -t lib/web/main.staging.dart --web-renderer canvaskit --source-maps --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false
```

**Comment by marandaneto** [comment]
@chathu-novade `release` and `dist` should match when initing the SDK and uploading source maps.
I see that you don't set the `dist` at least, do they match?
Can you provide a link to an Sentry's issue?

**Comment by marandaneto** [comment]
@chathu-novade you probably need `--release` in your build command line as well.

**Comment by chathu-novade** [comment]
`dist` is default so it get build in `build/web` which also the default of this plugin.

**Comment by chathu-novade** [comment]
@marandaneto 

```
https:
//sentry.io/organizations/novade/issues/
3543519896/
?project=1770595
```

**Comment by chathu-novade** [comment]
The flutter mobile builds works well Issue is with the web build

**Comment by marandaneto** [comment]
@chathu-novade I don't see any problem with your errors, its symbolicated correctly.
The issue title is `minified:e2b` because of https://docs.sentry.io/platforms/flutter/troubleshooting/#known-limitations
See `runtimeType`.
You are likely calling `captureException` with an object that is not an exception and its stringified, so there's no problem with symbolication.
Can you clarify the problem?

**Comment by chathu-novade** [comment]
> @chathu-novade you probably need `--release` in your build command line as well.

--release                          Build a release version of your app (default mode).

**Comment by marandaneto** [comment]
@chathu-novade that's already answered here https://github.com/getsentry/sentry-dart-plugin/issues/38#issuecomment-1231230647
If you don't see any frame from your own App, the reason is here https://github.com/getsentry/sentry-dart-plugin/issues/38#issuecomment-1231659696
So I guess that's all from my side unless you provide more context around my questions.

**Comment by chathu-novade** [comment]
About


> The issue title is `minified:e2b` because of https://docs.sentry.io/platforms/flutter/troubleshooting/#known-limitations
> See `runtimeType`.

Does this applicable to the web too?

web
Obfuscation is not supported for web apps, but a web app can be [minified](https://en.wikipedia.org/wiki/Minification_(programming)), which is similar. When you build a release version of a Flutter web app, it is automatically minified. For more information, see [Build and release a web app](https://docs.flutter.dev/deployment/web).

Is there sentry can

**Comment by marandaneto** [comment]
Please raise an issue on https://github.com/getsentry/sentry-dart and provide a minimal reproducible example (this is required), it's unclear what's the problem here since the linked event just works, without more context, we can't help.

**Comment by chathu-novade** [comment]
```
https 
://sentry.io/organizations/novade/issues/ 
3510915187/events/ 
bcaba367a7e74e92b0f7258900827d9a/
```

Check this issue and expand the stackstrace. We can not see which file threw the exception and not usable stack trace.
