### ISSUE TITLE
error: unsupported Zip archive

### ISSUE THREAD

**Issue by davidpanic** [getsentry/sentry-dart-plugin#44]
### Environment

`flutter: 3.3.0`
`sentry_dart_plugin: ^1.0.0-beta.2`

This was run in a GitLab CI environment with the docker image `cirrusci/flutter:stable`.
The CI logs report: `Using docker image sha256:9353de5b90829520a303fcc804b7fa8ed5ad07422811492be8c32888f398268a for cirrusci/flutter:stable with digest cirrusci/flutter@sha256:850c03338df79146ab9990ee7acd24a168713bf442b695936f4a645d15467131`

GitLab version: [15.3.3](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v15.3.3)
GitLab runner version: 15.1.0

### Steps to Reproduce

```yaml
sentry:
  upload_native_symbols: true
  upload_source_maps: true
  include_native_sources: true
  project: [redacted]
  org: [redacted]
  url: https://[redacted]/
  wait_for_processing: true
```

1. `flutter pub get`
2. `flutter packages pub run sentry_dart_plugin`

### Expected Result

I would expect the commands to succeed.

### Actual Result

```log
...stripped ~12 MB of other irrelevant logs...

  DEBUG   2022-09-07 12:24:20.935910615 +00:00 finished zip archive /builds/flutter/aio/.pub-cache/hosted/pub.dartlang.org/archive-3.3.0/test/tests/res/zip/test-trailing-junk.zip
  DEBUG   2022-09-07 12:24:20.935920090 +00:00 searching zip archive /builds/flutter/aio/.pub-cache/hosted/pub.dartlang.org/archive-3.3.0/test/tests/res/zip/password_zipcrypto.zip
error: unsupported Zip archive
  DEBUG   2022-09-07 12:24:20.941438106 +00:00 client close; no transport to shut down  (from sentry)
  DEBUG   2022-09-07 12:24:20.941448845 +00:00 skipping update nagger because session is not attended
stdout: 
pub finished with exit code 1
```

**Comment by marandaneto** [comment]
@kamilogorek shouldn't sentry-cli ignore those files?

**Comment by kamilogorek** [comment]
Yes, starting `2.2.0`, and this plugin is still using v1
