### ISSUE TITLE
Rename to sentry_plugin?

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dart-plugin#64]
Having dart in the name doesn't make that much sense on pub.dev - consider renaming to `sentry_plugin` (or is there a better name) before releasing the first version. Unfortunately, we can't rename a published package, the old one would need to be archived/deleted. Maybe the trouble is worth it 🤷 

Or maybe even move it to the main sentry_dart as an additional binary, so people don't have to add yet another dependency?

**Comment by marandaneto** [comment]
Sentry has many plugins and the `dart` in it helps to distinguish them, that was the idea, every other plugin has the platform name such as Sentry Android Gradle Plugin.

> Or maybe even move it to the main sentry_dart as an additional binary, so people don't have to add yet another dependency?

That would make it into the final binary increasing the App's bundle, or how else would you suggest?

**Comment by philipphofmann** [comment]
While I agree with your statement, @vaind, I think renaming it to `sentry_plugin` on pub.dev is not worth the hassle.

**Comment by vaind** [comment]
> Sentry has many plugins and the `dart` in it helps to distinguish them, that was the idea, every other plugin has the platform name such as Sentry Android Gradle Plugin.

yeah, I get that, though in my eyes that applies to the repo name, not the package name on pub.dev - the same way [this](https://pub.dev/packages/sentry) isn't called `sentry_dart`

> That would make it into the final binary increasing the App's bundle, or how else would you suggest?

not really, unless they actually use the code directly in their app - which isn't really a normal use case. 

------

> While I agree with your statement, @vaind, I think renaming it to sentry_plugin on pub.dev is not worth the hassle.

Totally got that

**Comment by marandaneto** [comment]
@vaind 

> not really, unless they actually use the code directly in their app - which isn't really a normal use case.

Do you mean adding as a `dev_dependency` or relying on Tree shaking?

**Comment by marandaneto** [comment]
@vaind we've agreed that renaming isn't worth the pain, so I'd close this issue, thanks for the feedback anyway.

> Or maybe even move it to the main sentry_dart as an additional binary, so people don't have to add yet another dependency?

This one actually makes sense and we'd like to discuss it further, would you like to raise a new issue for that?
