### ISSUE TITLE
Generated release name does not use Sentry project name

### ISSUE THREAD

**Issue by maxlapides** [getsentry/sentry-dart-plugin#66]
### Environment

sentry_dart_plugin: ^1.0.0-beta.4

### Steps to Reproduce

Set environment variables:
- `SENTRY_RELEASE` = `1.2.3+1234`
- `SENTRY_PROJECT` = `my-project`

Set `name` in `pubspec.yaml` to `app-name`

Run `flutter packages pub run sentry_dart_plugin`

### Expected Result

Create a release in Sentry named `my-project@1.2.3+1234`

### Actual Result

Created a release in Sentry named `app-name@1.2.3+1234`

The issue is right here:
https://github.com/getsentry/sentry-dart-plugin/blob/a948097eff00c8c1510f440520260cdc84153ccd/lib/sentry_dart_plugin.dart#L201

I think `_configuration.name` should be updated to `_configuration.project`. I can open a PR for this change, but I'm not 100% confident :)

**Comment by marandaneto** [comment]
`SENTRY_PROJECT` is the name of the project under sentry.io, which has nothing to do with your app's name.
If you want to change the 1st part of the release name, you should change the `name` under your `pubspec`.
