### ISSUE TITLE
"You do not have permission to perform this action." after updating beta.2 => beta.4

### ISSUE THREAD

**Issue by IvanDeluxe** [getsentry/sentry-dart-plugin#68]
### Environment

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.22621.674], locale hr-HR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.72.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```

### Steps to Reproduce

After updating from `beta.2` to `beta.4`:

```
call flutter pub get
call flutter pub run build_runner build --delete-conflicting-outputs
call flutter build web --release --source-maps
call flutter pub run sentry_dart_plugin
```

pubspec.yaml (placeholders shown)
```
sentry:
  upload_source_maps: true
  project: project_name
  org: org_name
  auth_token: auth_token
```

Forcing `beta.2` resolves the issue.

### Expected Result

The logs usually upload just fine.

### Actual Result

```
☑ uploading source maps

exitCode: 1
stderr: error: API request failed
  caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)
```

Thanks :)

**Comment by IvanDeluxe** [comment]
Yes, of course.

I do have both of those @ auth token.

Just in case, I've tried creating a new token, but nothing changes :(

Plus, if it means anything, this auth token works just fine @ version `beta.2`.

**Comment by marandaneto** [comment]
@IvanDeluxe try to disable the auto-commit config.

`commits: false` in your pubspec sentry config, maybe this requires more permission?
@vaind wanna double check?

**Comment by IvanDeluxe** [comment]
After setting `commits: true` it seems to work :)

I have to ask though: why?

Is this option harmful in any way?

Thanks!

**Comment by marandaneto** [comment]
@IvanDeluxe no, its a new feature, See the [docs](https://docs.sentry.io/product/cli/releases/#sentry-cli-commit-integration)
I guess this integration requires more permission but I'm unsure which one, I will double check.

**Comment by marandaneto** [comment]
@IvanDeluxe do you have a [repository configured](https://docs.sentry.io/product/releases/setup/release-automation/) in your sentry org? wondering if this could be the case.

**Comment by vaind** [comment]
> @IvanDeluxe do you have a [repository configured](https://docs.sentry.io/product/releases/setup/release-automation/) in your sentry org? wondering if this could be the case. Also set `log_level: debug` so we get better insights about the problem.

BTW I've tested without a repo configured

**Comment by vaind** [comment]
BTW I've also got this error recently and it turned out I've had auth token set both in `.sentryclirc` and as an environment variable, with the latter having fewer permissions and since that one was being used, I've had issues. 

You can see the first few characters of the token if you enable debug log & than look for `Authorization` header in the logs. That way you can make sure the CLI is actually using the token you're expecting it to use.

**Comment by IvanDeluxe** [comment]
Ahoy :D

Sorry for the late reply -- as I've stated above, setting `commits: false` fixed this for us :)

Also, we didn't set up repository integration.

**Comment by marandaneto** [comment]
Could be related to https://github.com/getsentry/sentry-cli/issues/1388 or not, still waiting for input from some other folks.

**Comment by andyhorn** [comment]
This same error occurred for us and was resolved by setting `commits: false` in our pubspec.

I used an auth token with the permissions: `project:read, project:releases, project:write`

**Comment by marandaneto** [comment]
@andyhorn per docs you'd need `org:read` as well.

**Comment by andyhorn** [comment]
Ahh, I only saw the scopes listed in the README and the line "To do this, you must have either a project:releases or project:write Scope." in the docs. I see there are more scopes required if I follow the link to the **Permissions & Scopes** page.

Can the README be updated to include this?

Thank you!

**Comment by marandaneto** [comment]
@andyhorn can you confirm that `org:read` would actually work?
Could also be related to:

> Are you using a personal token or an org token (from integrations)?

README has not changed because we've never gotten confirmation of the problem.

**Comment by andyhorn** [comment]
We have switched back over to an org token (that was previously also failing) after adding the `Organization - Read` permission and it succeeded 👍
