### ISSUE TITLE
Documentation on sentry.io/docs and Wizard

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart-plugin#83]
https://docs.sentry.io/platforms/flutter/upload-debug/#sentry-dart-plugin
https://github.com/getsentry/sentry-docs/blob/master/src/wizard/flutter/index.md?rgh-link-date=2022-09-07T07%3A32%3A25Z

We need to provide official documentation for the Sentry Dart Plugin under sentry.io/docs
Right now the documentation lives in the [README](https://github.com/getsentry/sentry-dart-plugin#available-configuration-fields) of the repo.
We also need to provide the install steps of the Sentry Dart Plugin on the Flutter Wizard.

**Comment by philipphofmann** [comment]
@marandaneto, please add more context to this issue. I need clarification on what it is about.

**Comment by marandaneto** [comment]
> @marandaneto, please add more context to this issue. I need clarification on what it is about.

Updated the description, the title should have been self-explanatory, sorry about that.

**Comment by marandaneto** [comment]
@denrase both options are fine, but then you have to link to this page anyway.
See what feels better/more natural.

We need to assume:

* Everyone needs the Dart plugin, so this is the first option.
* [uploading-with-proguard](https://docs.sentry.io/platforms/flutter/upload-debug/#uploading-with-proguard) is optional, only if you have `proguard` enabled.
* Parts of [uploading-for-android-ndk](https://docs.sentry.io/platforms/flutter/upload-debug/#uploading-for-android-ndk) can go to [troubleshooting](https://docs.sentry.io/platforms/flutter/troubleshooting/) since its an older version, and NDK symbols are uploaded by the Dart plugin as well
* [uploading-source-maps-for-flutter-web](https://docs.sentry.io/platforms/flutter/upload-debug/#uploading-source-maps-for-flutter-web) also optional since the Dart plugin uploads source maps as well
