### ISSUE TITLE
Stream sentry-cli output

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dart-plugin#87]
It would provide better UX if the CLI output got streamed instead of captured and printed in the end. As is, you may need to wait a long time without any feedback (not knowing if something got stuck). This is especially true if `wait_for_processing: true`.

**Comment by krystofwoldrich** [comment]
Would need an update on the `sentry-cli` to report an update on the process. Effort counts the changes in CLI.

**Comment by marandaneto** [comment]
Good point, that should be easy, thanks @vaind
