### ISSUE TITLE
integration-tests-sentry-cli.yml failing

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart-plugin#95]
> error: API request failed
>   caused by: sentry reported an error: unknown error (http status: 501)
>   DEBUG   2023-03-23 08:17:21.033209 +01:00 skipping update nagger because session is not attended
> 
> stdout: > Rewriting sources
> > Adding source map references
> > Bundled 0 files for upload
> > Uploaded release files to Sentry
> 
> Stopping the test-server ... /STOP request failed: Unable to read data from the transport connection: Connection reset by peer. - killing the server process instead
> ParentContainsErrorRecordException: /Users/user/Github/sentry-dart-plugin/integration-test/scripts/test.ps1:72
> Line |
>   72 |          $Callback.Invoke()
>      |          ~~~~~~~~~~~~~~~~~~
>      | Exception calling "Invoke" with "0" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Source map not uploaded"

**Comment by marandaneto** [comment]
@vaind do you know if something changed in the CLI? didn't check it yet but the integrations are failing.
IIRC `upload-dif` is now an alias to `debug-files upload` maybe the APIs changed too? Related to https://github.com/getsentry/team-mobile/issues/97
Just a hunch tho, have not investigated it yet.

**Comment by vaind** [comment]
Do you mean this change from the latest release? https://github.com/getsentry/sentry-cli/releases/tag/2.15.2

`fix: Make sourcemap injection on upload opt-in (https://github.com/getsentry/sentry-cli/pull/1534)`

sinde the error you've pasted says `Source map not uploaded`

**Comment by marandaneto** [comment]
@denrase this [part](https://github.com/getsentry/sentry-dart-plugin/blob/65a6e9bc3ddd4daa4affc727c4579569a79929c3/integration-test/scripts/test.ps1#L86-L104) is still very flaky.

> Checking symbol server output
> Verifying debug symbol upload...
>   app.so: count=3 - OK
>   libapp.so: count=3 - OK
>   libflutter.so: count=6 - OK
>   libhello_santry.so: count=12 - MISSING 
>     Server received '3' instead.
>   libhello_santry.so.sym: count=4 - OK
> Error: Process completed with exit code 1.

For some reason, `libhello_santry.so` is constantly changing, not sure why.

**Comment by vaind** [comment]
> @denrase this [part](https://github.com/getsentry/sentry-dart-plugin/blob/65a6e9bc3ddd4daa4affc727c4579569a79929c3/integration-test/scripts/test.ps1#L86-L104) is still very flaky.
> 
> > Checking symbol server output
> > Verifying debug symbol upload...
> > app.so: count=3 - OK
> > libapp.so: count=3 - OK
> > libflutter.so: count=6 - OK
> > libhello_santry.so: count=12 - MISSING
> > Server received '3' instead.
> > libhello_santry.so.sym: count=4 - OK
> > Error: Process completed with exit code 1.
> 
> For some reason, `libhello_santry.so` is constantly changing, not sure why.

I'd suggest looking at the reusable workflow... I did away with the strict checks. See a sample [test script](https://github.com/getsentry/sentry-dotnet/blob/0110385baedc3527d03652b4b6a9dbd8fe459029/test/sentry-cli-integration.Tests.ps1) and [CI job](https://github.com/getsentry/sentry-dotnet/blob/0110385baedc3527d03652b4b6a9dbd8fe459029/.github/workflows/build.yml#L63) in sentry-dotnet.
